// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnCSMnUffe1yhMwcGrk5GKT-x0Ps_Uq2s',
    appId: '1:650971444618:web:43b7474bbc487640cb4473',
    messagingSenderId: '650971444618',
    projectId: 'login-7d9db',
    authDomain: 'login-7d9db.firebaseapp.com',
    storageBucket: 'login-7d9db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYpKohaS2P9KdL7PEalUUp0nZwY2-VJ6M',
    appId: '1:650971444618:android:f15444b0ef76d8bacb4473',
    messagingSenderId: '650971444618',
    projectId: 'login-7d9db',
    storageBucket: 'login-7d9db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg461hske9JQ8XwvareKhQFXYLk2gV01Y',
    appId: '1:650971444618:ios:dd008f739b9d9fa9cb4473',
    messagingSenderId: '650971444618',
    projectId: 'login-7d9db',
    storageBucket: 'login-7d9db.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg461hske9JQ8XwvareKhQFXYLk2gV01Y',
    appId: '1:650971444618:ios:dd008f739b9d9fa9cb4473',
    messagingSenderId: '650971444618',
    projectId: 'login-7d9db',
    storageBucket: 'login-7d9db.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnCSMnUffe1yhMwcGrk5GKT-x0Ps_Uq2s',
    appId: '1:650971444618:web:4adb31c92047fe4bcb4473',
    messagingSenderId: '650971444618',
    projectId: 'login-7d9db',
    authDomain: 'login-7d9db.firebaseapp.com',
    storageBucket: 'login-7d9db.appspot.com',
  );

}